NewAuthDemo/config/routes.rb
NewAuthDemo::Application.routes.draw do
  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]
  
  get "/home/", to: "static_pages#home"
  get "/about/", to: "static_pages#about"
  get "/contact/", to: "static_pages#contact"
  
  root :to => "static_pages#home"
                      
end

NewAuthDemo/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :presence => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

NewAuthDemo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Expose these methods to the views
  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

  def require_signed_out!
    redirect_to user_url(current_user) if signed_in?
  end
end

NewAuthDemo/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_signed_out!, :only => [:new, :create]
  before_action :require_signed_in!, :only => [:destroy]

  def new
  end

  def create
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password]
    )

    if @user
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Invalid Credentials"]
      redirect_to root_url
    end
  end

  def destroy
    sign_out
    flash[:success] = ["Signed Out"]
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

NewAuthDemo/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
  
  def about
  end
  
  def contact
  end

end

NewAuthDemo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in!, :only => [:show]
  before_action :require_signed_out!, :only => [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Username or password error"]
      redirect_to root_url
    end
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

NewAuthDemo/app/helpers/application_helper.rb
module ApplicationHelper
end

NewAuthDemo/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

NewAuthDemo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YOLO sQuare</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://code.jquery.com/ui/1.11.1/jquery-ui.min.js"> </script>
    <%= csrf_meta_tags %>
    
  </head>
  <body data-spy="scroll" data-target=".navbar-scrolling">

    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button"
          class="navbar-toggle collapsed"
          data-toggle="collapse"
          data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span> 
          </button>
          <a href="#" class="navbar-brand">YOLO sQuare</a>
        </div>
        
        <div class="collapse navbar-collapse"
             id="bs-example-navbar-collapse-1">
             
          <ul id="sortable" class="nav navbar-nav">
            <li><%= link_to "Home", home_url %></li>
            <li><%= link_to "About", about_url %></li>
            <li><%= link_to "Contact", contact_url %></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            
          <% unless signed_in? %>        
            <li class="dropdown">
              <a href="#" class="dropdown-toggle"     
                          data-toggle="dropdown">
                          Sign in / Sign out
                          <span class="caret"></span>
              </a>
              

              <ul class="dropdown-menu" role="menu">
                  <li>
                    <a href="#" class="sign-in" data-toggle="modal" data-target="#signInModal">
                      Sign in
                    </a>
                  </li>
                  <li>
                    <a href="#" class="sign-up" data-toggle="modal" data-target="#signUpModal">
                      Sign up
                    </a>
                  </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "#{current_user.username}'s profile", current_user %></li>
            <li><%= button_to "Sign out, user `#{current_user.username}`",
                    session_url,
                    :class => "btn btn-primary", :method => :delete %>
            </li>
               
          <% end %>
          
          </ul>
        </div>
        
      </div>
    </nav>
        
    <div class="container">

      <div class="row errors-row">
        
        <div class="col-xs-6 col-xs-offset-1">

          <% if flash[:errors] %>
          <h3>Please fix the following errors:</h3>
          <ul>
            <% flash[:errors].each do |error| %>
            <li class="error"><%= error %></li>
            <% end %>
          </ul>
          <% end %>
          
          <% if flash[:success] %>
            <ul>
            <% flash[:success].each do |msg| %>
              <li><div class="alert-success"><%= msg %></div></li>
            <% end %>
            </ul>
          <% end %>
        
        </div>
        
      </div>
        
      <%= yield %>
      
    </div>
    
    <% unless current_user %>
      <div class="row">
        <div class="col-xs-4 col-xs-offset-1">    
          <%= render "users/form", user: (@user || User.new) %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-xs-4 col-xs-offset-1">    
         <%= render "sessions/form", user: (@user || User.new) %>
        </div>
      </div>  
    <% end %>

  </body>
</html>

NewAuthDemo/app/views/static_pages/about.html.erb
<div class="jumbotron">
  <h1>ABOUT</h1>
  
  <div class="row">
    
    <div class="col-xs-6">   
      <!-- start slipsum code -->
      <%= image_tag("1.jpg", class: "img-circle img-responsive") %>
     <p>
      The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee.
    </p>
      <!-- please do not remove this line -->
      <div style="display:none;">
      <a href="http://slipsum.com">lorem ipsum</a></div>
      <!-- end slipsum code -->     
    </div>
       
    <div class="col-xs-6">
      <%= image_tag("2.jpg", class: "img-responsive img-circle") %>
      <!-- start slipsum code -->    
      <p>
      You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man.
      </p>
      <!-- please do not remove this line -->
      <div style="display:none;">
      <a href="http://slipsum.com">lorem ipsum</a></div>
      <!-- end slipsum code -->
    </div>
    
  </div>
  
  <div class="row text-center">
  
    <div class="col-xs-3">
      <%= image_tag "team1.jpg", class: "img-responsive img-circle" %>
      <h2>Jam Sackson!</h2>
      <p>The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee.</p>
    </div>
    <div class="col-xs-3">
      <%= image_tag "team2.jpg", class: "img-responsive img-circle" %>
      <h2>Sam Jackson!</h2>    
      <p>Now that there is the Tec-9, a crappy spray gun from South Miami. This gun is advertised as the most popular gun in American crime. Do you believe that shit? It actually says that in the little book that comes with it: the most popular gun in American crime. Like they're actually proud of that shit. </p>
    </div>
    <div class="col-xs-3">
      <%= image_tag "team3.jpg", class: "img-responsive img-circle" %>
      <h2>Sam Jacksonovich!</h2>    
      <p>Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'?</p>
    </div>
    <div class="col-xs-3">
      <%= image_tag "team4.jpg", class: "img-responsive img-circle" %>
      <h2>Pam Jackson!</h2>    
      <p>Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass.</p>
    </div>
  
  </div>
    <div class="row text-center">
      <h1>Our Headquarters</h1>
      <div id="map-canvas" style="width: 800px; height: 400px; margin: 0 auto"></div>
      </div>
  
  </div>
  
</div>

<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBwOIJaG-DcYh4Af3qKflUzCvUcoQFOge0">
</script>
    
<script type="text/javascript">
    function initialize() {
      var mapOptions = {
        center: { lat: 34.08255, lng: -118.39953},
        zoom: 13
      };
      var map = new google.maps.Map(document.getElementById('map-canvas'),
          mapOptions);
      var markerCoords = new google.maps.LatLng(34.08255,-118.39953);
      var image = 'http://a.deviantart.net/avatars/s/a/samuelljacksonplz.png?1';
      // debugger;
      var marker = new google.maps.Marker({
          position: markerCoords,
          map: map,
          icon: image,
          draggable: true,
          animation: google.maps.Animation.DROP,
          title: "SAM JACKSON!"
      });
      google.maps.event.addListener(marker, 'click', toggleBounce);
      function toggleBounce() {

        if (marker.getAnimation() != null) {
          marker.setAnimation(null);
        } else {
          marker.setAnimation(google.maps.Animation.BOUNCE);
        }
      }
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

NewAuthDemo/app/views/static_pages/contact.html.erb
<h1>CONTACT</h1>

<div class="row">
  
  <div class="col-xs-6">
    
    <div class="alert" role="alert"></div>
    
    <form role="form">
      
      <div class="form-group">
        <label for="name-field">Your Name</label>
        <input type="text" id="name-field" class="form-control"/>
      </div>
      
      <div class="form-group">
        <label for="email-field">Your Email</label>
        <input type="text" id="email-field" class="form-control"/>
      </div>
      
      <div class="form-group">
        <label for="message-field">Your Email</label>
        <textarea id="message-field" class="form-control"></textarea>
      </div>
        
      <button class="btn btn-primary btn-listen-to">Submit</button>
    </form>
    
  </div>
  
  <div class="col-xs-6">
    <h3>Think about contacting us?</h3>
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>Number</th>
        <th>Email</th>
      </tr>
      <tr>
        <td>Max</td>
        <td>12345</td>
        <td>max@yolosquare.com</td>
      </tr>
      <tr>
        <td>Yuriy</td>
        <td>234456</td>
        <td>yuriy@yolosquare.com</td>
      </tr>
    </table>
  </div>
  
</div>

NewAuthDemo/app/views/static_pages/home.html.erb
<h1>HOME</h1>


<div class="row">
  
  <div class="col-xs-6 col-xs-offset-3">
    

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>    
      </ol>
  
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "cat1.jpg", style: "" %>
          <div class="carousel-caption">
            Professor P. Burgatron
          </div>
        </div>
    
        <div class="item">
          <%= image_tag "cat2.jpg", style: "width: 450px" %>
          <div class="carousel-caption">
            Princess Mira
          </div>
        </div>
    
        <div class="item">
          <%= image_tag "cat3.jpg", style: "" %>
          <div class="carousel-caption">
            Doctor Pucker, Ph.D.
          </div>
        </div>
      </div>
  
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>

    <div id="first">
    <p>You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. <a title="Shark ain't got SHIT " data-placement="right" data-toggle="tooltip" class="tooltip-image" href="#">Now we took an oath, that I'm breaking now</a>. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man. You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. <a title="Shark ain't got SHIT " data-placement="right" data-toggle="tooltip" class="tooltip-image" href="#">Now we took an oath, that I'm breaking now</a>. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man. You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. <a title="Shark ain't got SHIT " data-placement="right" data-toggle="tooltip" class="tooltip-image" href="#">Now we took an oath, that I'm breaking now</a>. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man.</p>
    </div>
    <div id="second">
    <p>My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when <a title="Badass Motherfucker" data-placement="top" data-toggle="tooltip" class="tooltip-image" href="#">I'm talking to you, motherfucker</a>. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand? My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when <a title="Badass Motherfucker" data-placement="top" data-toggle="tooltip" class="tooltip-image" href="#">I'm talking to you, motherfucker</a>. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand? My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when <a title="Badass Motherfucker" data-placement="top" data-toggle="tooltip" class="tooltip-image" href="#">I'm talking to you, motherfucker</a>. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?</p>
    </div>
    <div id="third">
    <p>Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. <a data-placement="top" data-toggle="tooltip" title="Some Motherfuckers ... " class="tooltip-image" href="#">Some don't, become nothing.</a> She starred in one of the ones that became nothing. Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. <a data-placement="top" data-toggle="tooltip" title="Some Motherfuckers ... " class="tooltip-image" href="#">Some don't, become nothing.</a> She starred in one of the ones that became nothing. Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. <a data-placement="top" data-toggle="tooltip" title="Some Motherfuckers ... " class="tooltip-image" href="#">Some don't, become nothing.</a> She starred in one of the ones that became nothing.</p>
    </div>
    <div id="fourth">
    <p>Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass. Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass. Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass.</p>
    </div>
    <div id="fifth">
    <p>Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends. Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends. Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.</p>
    </div>

  </div>

  <div class="col-xs-1 affix-top" data-spy="affix">
    <div class="navbar-scrolling affix-top">
      <ul class="nav nav-tabs" role="tablist">
        <li><a href="#first">first</a></li>
        <li><a href="#second">second</a></li>
        <li><a href="#third">third</a></li>
        <li><a href="#fourth">fourth</a></li>
        <li><a href="#fifth">fifth</a></li>
      </ul>
    </div>
  </div>
</div>

NewAuthDemo/app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>



<div class="modal fade"
     id="signUpModal"
     tabindex="-1"
     role="dialog" 
     aria-labelledby="signUpModalLabel" 
     aria-hidden="true">
     
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-header sign-up-modal">
        <h1>Create User</h1>
      </div>
      
      <div class="modal-body">
        <form action="<%= action %>" method="post" role="form">
          <input
             name="_method"
             type="hidden"
             value="<%= method %>">
          <input
             name="authenticity_token"
             type="hidden"
             value="<%= form_authenticity_token %>">

          <div class="form-group">
          <label for="user_username">Username</label>
          <input
             id="user_username"
             name="user[username]"
             type="text"
             class="form-control">
          </div>

          <div class="form-group">
          <label for="user_password">Password</label>
          <input
             id="user_password"
             name="user[password]"
             type="password"
             class="form-control">
          </div>
  
          <button class="btn btn-primary"><%= message %></button>
          <button type="button" class="btn btn-primary" data-dismiss="modal">
            Close
          </button>
        </form>
      </div>
    </div>
  </div>
  
</div>

NewAuthDemo/app/views/users/new.html.erb
</div>
  
  </div>

    <%= render "form", :user => @user %>

    <h1>Create User</h1>

  <div class="col-xs-4 col-xs-offset-1">    
  
<div class="row">

NewAuthDemo/app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>